Fix yards with area breaking facility search (#892)
Fixes #890

Yard areas found during search crashed the API because point geometries
were expected:
```
asyncpg.exceptions.InternalServerError: Argument to ST_X() must have type POINT
```

Original problem search `BODK` also works
<img width="1430" height="740" alt="image"
src="https://github.com/user-attachments/assets/5fdcfe61-70de-4a66-b13a-4c85d80c9e1e"
/>
<img width="1430" height="740" alt="image"
src="https://github.com/user-attachments/assets/5b9f06e6-2e7f-4e09-bb7e-44417930211a"
/>